# This is a config for E2B sandbox template.
# You can use template ID (cl9k7dceh0fe4boa9pky) or template name (fing-next-jsv1) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("fing-next-jsv1") # Sync sandbox
# sandbox = await AsyncSandbox.create("fing-next-jsv1") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('fing-next-jsv1')

team_id = "f5ef1890-c87e-4fdb-a1ef-bb87e5e64999"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "fing-next-jsv1"
template_id = "cl9k7dceh0fe4boa9pky"
