version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "3005:3005"
    environment:
      - NODE_ENV=production
      # Add other env vars as needed, e.g., from .env
      - db_api=${db_api}
      - db_messaging_id=${db_messaging_id}
      - db_app_id=${db_app_id}
    volumes:
      - ./api:/app
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped
