name: Process Issue
on: 
  issues:
    types: [closed]

jobs:
  process-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Print issue details
        run: |
          
          # Extracting values using awk to handle multiline
          project_name=$(echo "${{ github.event.issue.body }}" | awk '/### Project Name/{getline; print $0}' | sed 's/^[ \t]*//')
          project_description=$(echo "${{ github.event.issue.body }}" | awk '/### Project Description/{getline; print $0}' | sed 's/^[ \t]*//')
          project_url=$(echo "${{ github.event.issue.body }}" | awk '/### Project URL/{getline; print $0}' | sed 's/^[ \t]*//')
          discord_username=$(echo "${{ github.event.issue.body }}" | awk '/### Discord Username or Social Profile Link/{getline; print $0}' | sed 's/^[ \t]*//')
          github_repo=$(echo "${{ github.event.issue.body }}" | awk '/### GitHub Repository URL/{getline; print $0}' | sed 's/^[ \t]*//')
          additional_info=$(echo "${{ github.event.issue.body }}" | awk '/### Additional Information/{getline; print $0}' | sed 's/^[ \t]*//')
          contact_info=$(echo "${{ github.event.issue.body }}" | awk '/### Contact Information/{getline; print $0}' | sed 's/^[ \t]*//')

          # Printing the extracted values
          echo "Project Name: $project_name"
          echo "Project Description: $project_description"
          echo "Project URL: $project_url"
          echo "Discord Username/Social Profile Link: $discord_username"
          echo "GitHub Repository URL: $github_repo"
          echo "Additional Information: $additional_info"
          echo "Contact Information: $contact_info"
