name: Process Issue
on:
  issues:
    types: [closed]

jobs:
  process-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Print issue details as key-value pairs
        run: |
          echo "Issue Title: ${{ github.event.issue.title }}"
          echo "Issue Body:"
          echo "--------------------"
          echo "${{ github.event.issue.body }}"
          echo "--------------------"
