name: Process Issue
on:
  issues:
    types: [closed]

jobs:
  process-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Print issue details as JSON
        run: |
          ISSUE_TITLE=$(echo "$GITHUB_EVENT_ISSUE_TITLE" | jq -sR .)
          ISSUE_BODY=$(echo "$GITHUB_EVENT_ISSUE_BODY" | jq -sR .)
          
          echo "::set-output name=json_output::{\"title\": $ISSUE_TITLE, \"body\": $ISSUE_BODY }"
      
      - name: Output JSON
        run: |
          echo "${{ steps.print-issue-details-as-json.outputs.json_output }}"
