update_readme:
    name: Update Contributor Count in README
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository's code
      - name: Check out repository
        uses: actions/checkout@v4

      # Step 2: Get the total contributor count using the GitHub API
      - name: Get Contributor Count
        id: contributors
        run: |
          # This robust command finds the page number of the last page of contributors
          # to get an accurate total count, even for repos with over 100 contributors.
          COUNT=$(curl -s -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/Circuit-Overtime/elixpo_ai_chapter/contributors?per_page=1&anon=true" | \
          grep -Eo 'link:.*rel="last".*page=([0-9]+)' | grep -Eo '[0-9]+' | tail -n 1)
          
          # Fallback for repos with less than 100 contributors (one page)
          if [ -z "$COUNT" ]; then
            COUNT=$(curl -s -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/Circuit-Overtime/elixpo_ai_chapter/contributors?anon=true" | jq 'length')
          fi
          
          echo "Total contributors: $COUNT"
          echo "count=$COUNT" >> $GITHUB_OUTPUT

      # Step 3: Update the README.md file with the new count
      - name: Update Contributor Count in README
        run: |
          COUNT=${{ steps.contributors.outputs.count }}
          # This sed command finds the line: "- **[number]+ Global Contributors**"
          # and replaces the [number]+ part with the new $COUNT.
          sed -i -E "s/(- \\)\[0-9]+(\+)?\ (Global Contributors\\)/\1${COUNT} \3/" README.md

      # Step 4: Commit and push the changes back to the repository
      # This step only runs if the README.md file was actually changed.
      - name: Commit and push changes
        run: |
          # Configure git with the bot's identity
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          # Check if there are any changes to commit
          if ! git diff --quiet README.md; then
            echo "Changes detected. Committing and pushing..."
            git add README.md
            git commit -m "ci: Update contributor count in README"
            git push
          else
            echo "No changes to README.md. Contributor count is up-to-date."
          fi
