name: Process Issue
on:
  issues:
    types: [closed]

jobs:
  process-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Stash local changes
        run: |
          git stash

      - name: Append issue body to projects.json
        run: |
          BODY=$(echo "${{ github.event.issue.body }}" | jq -sR .)
          JSON_OBJECT="{\"content\": $BODY}"

          if [[ -f projects.json ]]; then
              if [[ $(jq '. | length' projects.json) -gt 0 ]]; then
                  jq ". += [$JSON_OBJECT]" projects.json > projects.json.tmp && mv projects.json.tmp projects.json
                  echo "" >> projects.json # Add a new line at end of file

              else
                   echo "[$JSON_OBJECT]" > projects.json
                  echo "" >> projects.json # Add a new line at end of file
              fi
          else
              echo "[$JSON_OBJECT]" > projects.json
              echo "" >> projects.json # Add a new line at end of file

          fi

      - name: Pull latest changes from remote
        run: |
          git pull origin main

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add projects.json
          git commit -m "Update projects.json with issue body"
          git push origin main

      - name: Apply stashed changes (if any)
        run: |
          git stash pop || echo "No stashed changes"
