name: Update Projects JSON
on:
  issues:
    types: [closed]

jobs:
  update_json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract issue data
        id: extract
        run: |
          # Extract form data from GitHub event payload (YAML form fields)
          ISSUE_BODY=$(jq -r '.issue.body' <<< '${{ toJSON(github.event) }}')

          # Extract individual fields using jq (structured YAML fields)
          PROJECT_NAME=$(jq -r '.issue.title' <<< '${{ toJSON(github.event) }}' | sed 's/\[New Project Title\]: //')
          PROJECT_DESCRIPTION=$(jq -r '.issue.body | capture("Project Description:\\n(?<desc>.*?)(\\n\\n|$)") | .desc' <<< "$ISSUE_BODY")
          PROJECT_URL=$(jq -r '.issue.body | capture("Project URL:\\n(?<url>.*?)(\\n\\n|$)") | .url' <<< "$ISSUE_BODY")
          DISCORD_USERNAME=$(jq -r '.issue.body | capture("Discord Username or Social Profile Link:\\n(?<discord>.*?)(\\n\\n|$)") | .discord' <<< "$ISSUE_BODY")
          GITHUB_REPO=$(jq -r '.issue.body | capture("GitHub Repository URL:\\n(?<repo>.*?)(\\n\\n|$)") | .repo' <<< "$ISSUE_BODY")
          ADDITIONAL_INFO=$(jq -r '.issue.body | capture("Additional Information:\\n(?<info>.*?)(\\n\\n|$)") | .info' <<< "$ISSUE_BODY")
          CONTACT_INFO=$(jq -r '.issue.body | capture("Contact Information:\\n(?<contact>.*?)(\\n\\n|$)") | .contact' <<< "$ISSUE_BODY")

          # Export variables for later steps
          echo "PROJECT_NAME=$PROJECT_NAME" >> $GITHUB_ENV
          echo "PROJECT_DESCRIPTION=$PROJECT_DESCRIPTION" >> $GITHUB_ENV
          echo "PROJECT_URL=$PROJECT_URL" >> $GITHUB_ENV
          echo "DISCORD_USERNAME=$DISCORD_USERNAME" >> $GITHUB_ENV
          echo "GITHUB_REPO=$GITHUB_REPO" >> $GITHUB_ENV
          echo "ADDITIONAL_INFO=$ADDITIONAL_INFO" >> $GITHUB_ENV
          echo "CONTACT_INFO=$CONTACT_INFO" >> $GITHUB_ENV

      - name: Update projects.json
        run: |
          # Ensure projects.json exists
          if [ ! -f projects.json ]; then
            echo "[]" > projects.json
          fi

          # Append extracted data to JSON
          jq '. + [{
            "project_name": "${{ env.PROJECT_NAME }}",
            "description": "${{ env.PROJECT_DESCRIPTION }}",
            "url": "${{ env.PROJECT_URL }}",
            "discord_username": "${{ env.DISCORD_USERNAME }}",
            "github_repo": "${{ env.GITHUB_REPO }}",
            "additional_info": "${{ env.ADDITIONAL_INFO }}",
            "contact_info": "${{ env.CONTACT_INFO }}"
          }]' projects.json > temp.json && mv temp.json projects.json

      - name: Commit changes
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add projects.json
          git commit -m "Update projects.json with new project submission" || echo "No changes to commit"

          # Authenticate using PAT_TOKEN
          git remote set-url origin https://x-access-token:${PAT_TOKEN}@github.com/${{ github.repository }}.git
          git push origin HEAD:main
