name: Process Project Submission

on:
  issues:
    types: [closed]

jobs:
  extract-and-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Extract Issue Data
        id: extract_data
        run: |
          ISSUE_BODY="${{ github.event.issue.body }}"
          
          # Extract values safely, replacing empty fields with "null"
          extract_field() {
            echo "$ISSUE_BODY" | grep -oP "(?<=### $1\n).*" | tr -d '\r' || echo "null"
          }

          PROJECT_NAME=$(extract_field "Project Name")
          PROJECT_DESCRIPTION=$(extract_field "Project Description")
          PROJECT_URL=$(extract_field "Project URL")
          DISCORD_USERNAME=$(extract_field "Discord Username or Social Profile Link")
          GITHUB_REPO=$(extract_field "GitHub Repository URL")
          ADDITIONAL_INFO=$(extract_field "Additional Information")
          CONTACT_INFO=$(extract_field "Contact Information")

          # Ensure null replacement if fields are truly empty
          PROJECT_NAME=${PROJECT_NAME:-null}
          PROJECT_DESCRIPTION=${PROJECT_DESCRIPTION:-null}
          PROJECT_URL=${PROJECT_URL:-null}
          DISCORD_USERNAME=${DISCORD_USERNAME:-null}
          GITHUB_REPO=${GITHUB_REPO:-null}
          ADDITIONAL_INFO=${ADDITIONAL_INFO:-null}
          CONTACT_INFO=${CONTACT_INFO:-null}

          echo "Extracted values:"
          echo "Project Name: $PROJECT_NAME"
          echo "Project Description: $PROJECT_DESCRIPTION"
          echo "Project URL: $PROJECT_URL"
          echo "Discord Username: $DISCORD_USERNAME"
          echo "GitHub Repo: $GITHUB_REPO"
          echo "Additional Info: $ADDITIONAL_INFO"
          echo "Contact Info: $CONTACT_INFO"

          # Create JSON entry
          NEW_ENTRY=$(jq -n \
            --arg name "$PROJECT_NAME" \
            --arg desc "$PROJECT_DESCRIPTION" \
            --arg url "$PROJECT_URL" \
            --arg discord "$DISCORD_USERNAME" \
            --arg repo "$GITHUB_REPO" \
            --arg info "$ADDITIONAL_INFO" \
            --arg contact "$CONTACT_INFO" \
            '{project_name: ($name // "null"), project_description: ($desc // "null"), project_url: ($url // "null"), discord_username: ($discord // "null"), github_repo: ($repo // "null"), additional_info: ($info // "null"), contact: ($contact // "null")}')
          
          echo "NEW_ENTRY=$NEW_ENTRY" >> $GITHUB_ENV

      - name: Update projects.json
        run: |
          if [ ! -f projects.json ]; then
            echo "[]" > projects.json
          fi
          
          jq '. += [$NEW_ENTRY]' projects.json > tmp.json && mv tmp.json projects.json

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add projects.json
          git commit -m "Add new project entry from issue #${{ github.event.issue.number }}"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
